openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: Amazon Macie 2 Admin#adminAccountId Resource Profiles#resourceArn API
  description: Amazon Macie
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: macie2
  x-aws-signingName: macie2
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/macie2-2020-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://macie2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Macie 2 multi-region endpoint
- url: https://macie2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Macie 2 multi-region endpoint
- url: http://macie2.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Macie 2 endpoint for China (Beijing) and China (Ningxia)
- url: https://macie2.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Macie 2 endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Resource Profiles#resourceArn
paths:
  /resource-profiles#resourceArn:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: GetResourceProfile
      description: Retrieves (queries) sensitive data discovery statistics and the sensitivity score for an S3 bucket.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResourceProfileResponse'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '482':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '483':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '485':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: resourceArn
        in: query
        required: true
        description: The Amazon Resource Name (ARN) of the S3 bucket that the request applies to.
        schema:
          type: string
      summary: Amazon Macie Get Resource Profile
      tags:
      - Resource Profiles#resourceArn
    patch:
      operationId: UpdateResourceProfile
      description: Updates the sensitivity score for an S3 bucket.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResourceProfileResponse'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '482':
          description: ServiceQuotaExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '483':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '484':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '485':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: resourceArn
        in: query
        required: true
        description: The Amazon Resource Name (ARN) of the S3 bucket that the request applies to.
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sensitivityScoreOverride:
                  description: 'The new sensitivity score for the bucket. Valid values are: 100, assign the maximum score and apply the <i>Sensitive</i> label to the bucket; and, null (empty), assign a score that Amazon Macie calculates automatically after you submit the request.'
                  type: integer
      summary: Amazon Macie Update Resource Profile
      tags:
      - Resource Profiles#resourceArn
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    InternalServerException: {}
    __integer:
      type: integer
    ThrottlingException: {}
    UpdateResourceProfileResponse:
      type: object
      properties: {}
    GetResourceProfileResponse:
      type: object
      properties:
        profileUpdatedAt:
          allOf:
          - $ref: '#/components/schemas/__timestampIso8601'
          - description: The date and time, in UTC and extended ISO 8601 format, when Amazon Macie most recently recalculated sensitive data discovery statistics and details for the bucket. If the bucket's sensitivity score is calculated automatically, this includes the score.
        sensitivityScore:
          allOf:
          - $ref: '#/components/schemas/__integer'
          - description: The current sensitivity score for the bucket, ranging from -1 (classification error) to 100 (sensitive). By default, this score is calculated automatically based on the amount of data that Amazon Macie has analyzed in the bucket and the amount of sensitive data that Macie has found in the bucket.
        sensitivityScoreOverridden:
          allOf:
          - $ref: '#/components/schemas/__boolean'
          - description: Specifies whether the bucket's current sensitivity score was set manually. If this value is true, the score was manually changed to 100. If this value is false, the score was calculated automatically by Amazon Macie.
        statistics:
          allOf:
          - $ref: '#/components/schemas/ResourceStatistics'
          - description: The sensitive data discovery statistics for the bucket. The statistics capture the results of automated sensitive data discovery activities that Amazon Macie has performed for the bucket.
    ResourceStatistics:
      type: object
      properties:
        totalBytesClassified:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total amount of data, in bytes, that Amazon Macie has analyzed in the bucket.
        totalDetections:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of occurrences of sensitive data that Amazon Macie has found in the bucket's objects. This includes occurrences that are currently suppressed by the sensitivity scoring settings for the bucket (totalDetectionsSuppressed).
        totalDetectionsSuppressed:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of occurrences of sensitive data that are currently suppressed by the sensitivity scoring settings for the bucket. These represent occurrences of sensitive data that Amazon Macie found in the bucket's objects, but the occurrences were manually suppressed. By default, suppressed occurrences are excluded from the bucket's sensitivity score.
        totalItemsClassified:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of objects that Amazon Macie has analyzed in the bucket.
        totalItemsSensitive:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of the bucket's objects that Amazon Macie has found sensitive data in.
        totalItemsSkipped:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: '<p>The total number of objects that Amazon Macie hasn''t analyzed in the bucket due to an error or issue. For example, the object is a malformed file. This value includes objects that Macie hasn''t analyzed for reasons reported by other statistics in the ResourceStatistics object.</p> '
        totalItemsSkippedInvalidEncryption:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of objects that Amazon Macie hasn't analyzed in the bucket because the objects are encrypted with a key that Macie isn't allowed to use.
        totalItemsSkippedInvalidKms:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of objects that Amazon Macie hasn't analyzed in the bucket because the objects are encrypted with an KMS key that was disabled or deleted.
        totalItemsSkippedPermissionDenied:
          allOf:
          - $ref: '#/components/schemas/__long'
          - description: The total number of objects that Amazon Macie hasn't analyzed in the bucket because Macie isn't allowed to access the objects.
      description: Provides statistical data for sensitive data discovery metrics that apply to an S3 bucket that Amazon Macie monitors and analyzes for your account. The statistics capture the results of automated sensitive data discovery activities that Macie has performed for the bucket. The data is available only if automated sensitive data discovery is currently enabled for your account.
    ServiceQuotaExceededException: {}
    __long:
      type: integer
    __boolean:
      type: boolean
    __timestampIso8601:
      type: string
      format: date-time
    ResourceNotFoundException: {}
    AccessDeniedException: {}
    ValidationException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/macie2/
x-hasEquivalentPaths: true
